spring.application.name=ms-productos
server.port=8081
server.servlet.context-path=/api


spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.yjjegavoizzmqmpamdyi
spring.datasource.password=fpatFtTW2tewr9sD

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Logging
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.com.milsabores=DEBUG

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# CORS
app.cors.allowed-origins=http://localhost:5173

# Supabase JWT
supabase.jwks=https://yjjegavoizzmqmpamdyi.supabase.co/auth/v1/keys
supabase.issuer=https://yjjegavoizzmqmpamdyi.supabase.co/auth/v1


mvn spring-boot:run -Djava.net.preferIPv4Stack=true
